parameters:
    berriart_sitemap.class: Berriart\Bundle\SitemapBundle\Manager\Sitemap
    berriart_sitemap.controller.class: Berriart\Bundle\SitemapBundle\Controller\SitemapController
    berriart_sitemap.entity.url.class: Berriart\Bundle\SitemapBundle\Entity\Url
    berriart_sitemap.repository.url.class: Berriart\Bundle\SitemapBundle\Repository\UrlRepository
    berriart_sitemap.provider.chain.class: Berriart\Bundle\SitemapBundle\Provider\UrlProviderChain
    berriart_sitemap.twig.extension.class: Berriart\Bundle\SitemapBundle\Twig\SitemapExtension

services:
    berriart_sitemap:
        class: %berriart_sitemap.class%
        arguments: ["@berriart_sitemap.repository.url", "%berriart_sitemap.config.url_limit%", "%berriart_sitemap.config.multidomain%", "%berriart_sitemap.config.base_url%"]
    berriart_sitemap.controller:
        class: %berriart_sitemap.controller.class%
        calls:
            - [ "setContainer", [ "@service_container" ]]
    berriart_sitemap.repository.url:
        class: %berriart_sitemap.repository.url.class%
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ["%berriart_sitemap.entity.url.class%"]
    berriart_sitemap.provider.chain:
        class: %berriart_sitemap.provider.chain.class%
    berriart_sitemap.twig.extension:
        class: %berriart_sitemap.twig.extension.class%
        arguments: ["%berriart_sitemap.config.base_url%"]
        tags:
            -  { name: twig.extension }
    %berriart_sitemap.config.alias%:
        alias: berriart_sitemap
